### ISSUE TITLE
[BUG]: End of Enterprise section abruptly stops mid-thought

### ISSUE THREAD

**Issue by cparlette** [triggermesh/docs#237]
## Description
This is currently the last line of the 'Enterprise' section at https://docs.triggermesh.io/cloud/#for-cli-lovers

"For example you will be able to bypass the console and do something like this:"

## Screenshots
<img width="699" alt="Screen Shot 2021-12-09 at 11 19 08 AM" src="https://user-images.githubusercontent.com/1018563/145434472-9815b0e5-e448-4985-8cf9-ae0d07a656eb.png">

**Comment by jmcx** [comment]
this section won't exist anymore in the new version of the docs
