### ISSUE TITLE
[ENHANCEMENT]: Add details of S3 ARN requirements to AWSS3Target

### ISSUE THREAD

**Issue by cparlette** [triggermesh/docs#239]
## Description
The ARN string of an S3 bucket as given by AWS looks like this:

arn:aws:s3:::{bucket_name}

The AWSS3Target requires the ARN to look like this:

arn:aws:s3:{aws_region}:{aws_account_id}:{bucket_name}

This is detailed in https://docs.triggermesh.io/cloud/sources/awss3/#amazon-resource-name-arn , but it is not obvious to look at this page for the AWSS3Target.

**Comment by antoineco** [comment]
No longer the case since https://github.com/triggermesh/triggermesh/pull/489.
Closing
