### ISSUE TITLE
[ENHANCEMENT]: Sources and Targets linkable pages

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/docs#315]
In the list of contents, `Sources` and `Targets` don't have their own "home" page, they are not linkable:
<img width="282" alt="Screenshot 2022-11-26 at 4 02 15 PM" src="https://user-images.githubusercontent.com/13515865/204083149-0f908cfc-d6b4-4986-a7fc-78b32adb4f21.png">

I think it can be helpful to have documentation links in the CLI subcommand. Below, I put the links for everything but sources and targets, because there is no such links right now. This home page could contain a "source" or "target" definition and a list of the available components.

```
$ tmctl create --help
Create TriggerMesh component
...
Available Commands:
  broker         Create TriggerMesh Broker. More information at https://docs.triggermesh.io/brokers/
  source         Create TriggerMesh source
  target         Create TriggerMesh target
  transformation Create TriggerMesh transformation. More information at https://docs.triggermesh.io/transformation/jsontransformation/
  trigger        Create TriggerMesh trigger. More information at https://docs.triggermesh.io/brokers/triggers/
...
```

**Comment by sebgoa** [comment]
@jmcx I think that's a mkdocs issue, I remember struggling to do this without creating an index page.

**Comment by jmcx** [comment]
added some redirects in https://github.com/triggermesh/docs/commit/36bf6aa3bd6b28e8bf1696d2d706be83a4267f96

You can now link to these things (with or without trailing slash):
* https://docs.triggermesh.io/get-started
* https://docs.triggermesh.io/sources
* https://docs.triggermesh.io/targets
* https://docs.triggermesh.io/guides
* https://docs.triggermesh.io/reference

**Comment by jmcx** [comment]
The easiest but also IMO useful solution I implemented is to just use redirects, so /sources will redirect to the first source in the list. This avoids creating additional index pages which don't have much value and need to be maintained. But we could of course also created index pages if needed.
