### ISSUE TITLE
Use the 3rd person consistently

### ISSUE THREAD

**Issue by antoineco** [triggermesh/docs#34]
> For technical documentation, have been taught to use the 3rd person in order to remove the perception of bias and also remove a sense of familiarity.

_Originally posted by @cab105 in https://github.com/triggermesh/docs/pull/29_

We should modify all pages that use the 2nd person, and remember to follow this rule in the future.

**Comment by antoineco** [comment]
A note: after thinking about this, I must admit I strongly disagree with the "rule" proposed here, because it prevents us from using any formulation such as "you can obtain foo" or "click too" which feels very natural for me to use in docs.

My 2c.

**Comment by sebgoa** [comment]
yeah....using "you" is most widely used I think. We should punt this to our future technical writer when we have one.

**Comment by cab105** [comment]
I'm okay with dropping this one as it would vary depending on context.

**Comment by antoineco** [comment]
Closing because not always applicable for that type of documentation. Also, the second person gives a sense of proximity which I _think_ a lot of companies try to achieve in their user docs nowadays.
