### ISSUE TITLE
Add docs for all targets and sources

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/docs#45]
**Sources**

- [x] awscodecommit
- [ ] awscognitoidentity
- [x] awscognitouserpool (#77)
- [x] awsdynamodb
- [ ] ~awsiot~
- [x] awskinesis
- [x] awssns (#83)
- [x] awssqs
- [x] azureactivitylogs
- [x] azureblobstorage (#117)
- [ ] azureeventhub (#56)
- [x] salesforce
- [x] http (#76)
- [x] ocimentrics (#54)
- [x] slack (#63)
- [x] zendesk

**Targets**

- [x] awslambda (#56)
- [x] awssns (#56)
- [x] awssqs (#56)
- [x] awskinesis (#56)
- [x] awss3 (#56)
- [x] awseventbridge
- [x] confluent (#75)
- [x] datadog (#61)
- [x] elasticsearch
- [x] googlesheet (#65)
- [x] hasura
- [x] http (#78)
- [ ] infra - Pablo -
- [x] oracle (#54)
- [x] sendgrid
- [x] slack (#63)
- [x] splunk
- [x] tekton (#65)
- [x] twilio
- [x] zendesk

**Comment by cab105** [comment]
Note, the slack target has been updated and is in good shape.

**Comment by sameersbn** [comment]
Update: AWS SQS Source has been documented via https://github.com/triggermesh/docs/pull/57

**Comment by sebgoa** [comment]
@odacremolbap should do the http and infra target

@cab105 is the best positioned for tekton

**Comment by odacremolbap** [comment]
Yes we should

**Comment by cab105** [comment]
> 
> 
> @odacremolbap should do the http and infra target
> 
> @cab105 is the best positioned for tekton

I'm assuming this also applies for the sources as well?
