### ISSUE TITLE
The tm installation page refers to a Brew Tap which is outdated.

### ISSUE THREAD

**Issue by antoineco** [triggermesh/docs#89]
https://docs.triggermesh.io/tm/install/

**Comment by sebgoa** [comment]
@tzununbekov can you update the brew tap with latest tm here: https://github.com/triggermesh/homebrew-tap

thanks

**Comment by sebgoa** [comment]
or @sameersbn actually, maybe you can bake that into cyberwoodford

**Comment by sameersbn** [comment]
yea i'll take this. but instead of updating this tap, i'll contribute the package to the [homebrew-core])https://github.com/Homebrew/homebrew-core) library. Once it's in there, their system automatically updates the packages on new github releases.

**Comment by sameersbn** [comment]
created https://github.com/triggermesh/homebrew-tap/issues/1

**Comment by sameersbn** [comment]
`tm` is now part of the office brew repo. will update the docs to reflect this
